import { resolve, dirname } from 'path';
import fs from 'fs';
import { ConfigObject } from '../types/plugin';

/**
 * 写入类型文件（如果内容发生变化，避免不必要的磁盘写入）
 * @param filePath 文件路径
 * @param content 文件内容
 */
function writeTypeFileIfChanged(filePath: string, content: string): void {
  // 确保目录存在
  fs.mkdirSync(dirname(filePath), { recursive: true });

  let needWrite = true;
  if (fs.existsSync(filePath)) {
    const oldContent = fs.readFileSync(filePath, 'utf8');
    if (oldContent === content) {
      needWrite = false;
    }
  }

  if (needWrite) {
    fs.writeFileSync(filePath, content, 'utf8');
  }
}

/**
 * 生成路由类型声明文件
 * @param pageNames 页面路径数组（如 '/pages/home/index'）
 * @param options 插件配置对象
 * @returns 生成的类型文件绝对路径
 */
export function generateRouteTypes(pageNames: string[], options: ConfigObject): string {
  const typeStr = `// Generated by unplugin-auto-import\nexport type Path = ${pageNames
    .map((n) => `'${n}'`)
    .join(' | ')};\n`;

  // 目标路径优先取 options.dts，否则 src/auto-route.d.ts
  const dtsPath = options.dts ? resolve(process.cwd(), options.dts) : resolve(process.cwd(), 'src/auto-route.d.ts');

  writeTypeFileIfChanged(dtsPath, typeStr);

  return dtsPath;
}
